
export const CONTINENT_COUNTRIES = {
  Asia: [
    "Armenia",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Brunei",
    "Cambodia",
    "China",
    "Hong Kong",
    "Indonesia",
    "Iran",
    "Israel",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Korea",
    "Kuwait",
    "Laos",
    "India",
    "Lebanon",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "Oman",
    "Pakistan",
    "Philippines",
    "Qatar",
    "Russia",
    "Saudi-Arabia",
    "Singapore",
    "Syria",
    "Sri Lanka",
    "Taiwan",
    "Thailand",
    "Turkey",
    "UAE",
    "Uzbekistan",
    "Vietnam",
    "Yemen",
  ],

  Africa: [
    "Algeria",
    "Angola",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Chad",
    "Congo",
    "Cote D'Ivoire",
    "Egypt",
    "Ethiopia",
    "Ghana",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Sierra Leone",
    "South Africa",
    "Tanzania",
    "Namibia",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
  ],

  Europe: [
    "Austria",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Luxembourg",
    "Lithuania",
    "Malta",
    "Moldova",
    "Netherlands",
    "North Macedonia",
    "Poland",
    "Portugal",
    "Romania",
    "Serbia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "UK",
    "Ukraine",
  ],

  "North America": [
    "Canada",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Jamaica",
    "Mexico",
    "Nicaragua",
    "Panama",
    "US",
  ],

  Oceania: [
    "Australia",
    "Fiji",
    "New Zealand",
    "Papua New Guinea",
  ],

  "South America": [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Venezuela",
    "Uruguay",
  ],
};

export function getContinent(country = "") {
  const normalizedCountry = country.trim().toLowerCase();

  for (const [continent, countries] of Object.entries(
    CONTINENT_COUNTRIES
  )) {
    const found = countries.find(
      (item) => item.toLowerCase() === normalizedCountry
    );

    if (found) {
      return continent;
    }
  }

  return "Asia"; // fallback
}